language: node_js
sudo: false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_c70b7fb2ead1_key -iv $encrypted_c70b7fb2ead1_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'huanz'
- git config --global user.email 'yhz1219@gmail.com'
script:
- git clone git@git.coding.net:bukas/surge.git
- cp ChinaUnicom.conf ChinaNet.conf CMCC.conf surge
- cd surge && git add -u && git commit -m 'update by travis at $(date -u +"%Y-%m-%d %H:%M:%S")' && git push
