sudo: false
language: node_js
node_js:
- 4
branches:
  only:
  - source
before_install:
- cp -r .leancloud ~
install:
- npm install -g avoscloud-code
script:
- lean deploy -g -r 'source' -o 'deploy by travis'
